# Generated by Django 3.0.7 on 2020-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('name', models.CharField(default='', max_length=32)),
                ('os', models.CharField(default='', max_length=64)),
                ('kernel', models.CharField(default='', max_length=64)),
                ('cpu_number', models.IntegerField(default=0)),
                ('cpu_core', models.IntegerField(default=0)),
                ('cpu_vcore', models.IntegerField(default=0)),
                ('arch', models.CharField(default='x86', max_length=16)),
                ('mem_info', models.CharField(default='[]', max_length=512)),
                ('disk_info', models.CharField(default='{}', max_length=512)),
                ('gpu_info', models.CharField(default='', max_length=512)),
                ('remark', models.TextField(default='')),
                ('project_name', models.CharField(default='ESD', max_length=64)),
                ('discover_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
